export const ROUTES = Object.freeze({
	login: "Login",
	home: "Dashboard",
	bio: "Bio",
	job: "Job",
	employmentHistory: "Employment History",
	certifications: "Certifications",
	confirmation: "Confirmation",
	hrDashboard: "HR Dashboard",
	hrEmployees: "HR Employees",
	staffDashboard: "Staff Dashboard",
	employees: "Employees",
	projects: "Projects",
	leave: "Leave",
	hrLeave: "HR Leave",
	viewTeamLeaveInfo: "View Team Leave",
	managerViewLeaveApplications: "View Team Applications",
	departments: "Departments",
	changePassword: "Change Password",
	userInfo: "User Info",

	admin: {
		employees: "Admin Employees",
		departments: "Admin Departments",
	},
	hr: {
		dashboard: "HR Dashboard",
		employees: "HR Employees",
		leave: "HR Leave",
	},
	manager: {
		dashboard: "Manager Dashboard",
		bio: "Manager Bio",
		jobDetails: "Manager Job Details",
		employmentHistory: "Manager Employment History",
		certifications: "Manager Certifications",
		confirmation: "Manager Confirmation",
		projects: "Manager Projects",
		leave: "Manager Leave",
		viewTeamInfo: "Manager View Team Leave Info",
	},
	staff: {
		dashboard: "Staff Dashboard",
		bio: "Staff Bio",
		jobDetails: "Staff Job Details",
		employmentHistory: "Staff Employment History",
		certifications: "Staff Certifications",
		confirmation: "Staff Confirmation",
		projects: "Staff Projects",
		leave: "Staff Leave",
	},
})
